<?php

namespace Bd\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FgroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FgroupRepository extends EntityRepository
{
}
