bd_imhotep_homepage:
    pattern:  /
    defaults: { _controller: BdImhotepBundle:Imhotep:index }
issue:
    pattern:  /issue
    defaults: { _controller: BdImhotepBundle:Issue:index }    
bd_issue_new:
    pattern:  /new
    defaults: { _controller: BdImhotepBundle:Issue:new }
issue_create:
    pattern:  /create
    defaults: { _controller: BdImhotepBundle:Issue:create }       
bd_project_new:
   pattern:  /addproject
   defaults: { _controller: BdImhotepBundle:Project:new }
project:
   pattern:  /issue
   defaults: { _controller: BdImhotepBundle:Project:index } 
project_create:
    pattern:  /createproject
    defaults: { _controller: BdImhotepBundle:Project:create } 