parameters:
#    bd_imhotep.example.class: Bd\ImhotepBundle\Example

services:
#    bd_imhotep.example:
#        class: %bd_imhotep.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
